### ISSUE TITLE
✅ Homework Feedback #3

### ISSUE THREAD

**Issue by cmota** [sc0des/picture_screen#1]
Hello 👋,

Great work! There's just a really small tweak missing to have the same UI as the one in the exercise.

Really like the path you've followed to `hide` the action bar and to include the `image_info`! 

Keep up with the good work! 🙌

### Grade

98/100

### UI differences

There's just a small difference that I need to mention.

When including the `image_info` layout you've defined its width to be `379dp`. Although on your emulator it might seem centered on the screen, the problem with using hardcoded values like this one is when running on a device with a different resolution, it might look different, which is the case when I run the app on mine.

As an improvement, you should use:

```
android:layout_width="match_parent"
```

That guarantees that it's going to be centered on all devices.

**Comment by sc0des** [comment]
Thank you for the feedback, I will update it
